### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by Hakameda**
i'll make a proper thing to test tonight before submitting PR's

### CODE REVIEW

**Comment by Hakameda** [comment]
Crushed Tungsten, Crushed Gypsum does seem to work. I had actually sifted one the build before last

**Comment by Hakameda** [comment]
Also changed tungsten to tungstate

**Comment by Quantum64** [comment]
There is still no crushed gypsum ore in regular GT. This causes a game crash.

**Comment by Hakameda** [comment]
So is it something gtnh does? Cause if I load it. It works

**Comment by Quantum64** [comment]
Looks like it

**Comment by Hakameda** [comment]
Should change to impure gypsum or clean gypsum I suppose

**Comment by Quantum64** [comment]
Those don't exist either, also gypsum isn't used in any GT recipes.

**Comment by Hakameda** [comment]
It can just be removed then, will just be for gtnh

**Pull request closed without merging**
