### PR TITLE
Changing drops slightly

### PR DESCRIPTION
**Pull request by Hakameda**
Magnetite to Iron, 
Increased chances of common Iron/Tin/Copper
Added Tungsten

### CODE REVIEW

**Comment by Hakameda** [comment]
I hope i did that right?

**Comment by Quantum64** [comment]
The reason it's saying checks failed is because it's trying to do a deployment to releases when you don't have access to the repo. I'll setup a different build configuration for PRs at some point.

**Comment by Quantum64** [comment]
And it had a compiletime issue 2de91440242733c5115621cedf571a5e67ecd465

**Comment by Hakameda** [comment]
yeah i'm trying to get it working so i can test it before i hit that. Not much of a clue of what im doing =p

**Comment by Hakameda** [comment]
It was this dumb as this - error: ')' expected

I copied the line but missed a bracket

**Pull request merged**
